### ISSUE TITLE
Provide fallback search registries if the OS does not configure any

### ISSUE THREAD

**Issue by amanjohar** [cockpit-project/cockpit-podman#777]
Debian 11, cockpit-podman backports fresh install.

Unable to search for images.

![image](https://user-images.githubusercontent.com/6968533/135699270-7a1cc457-9ace-4e16-812b-3381eb3bfde8.png)

Missing registries entries.

**Comment by amanjohar** [comment]
podman pull works properly in the shell. can someone help me fix this.

**Comment by amanjohar** [comment]
Edit the /etc/containers/registries.conf and add the following lines to fix this.

[registries.search]
registries = ['docker.io', 'registry.fedoraproject.org', 'quay.io', 'registry.access.redhat.com', 'registry.centos.org']

Save and restart podman and cockpit.

**Comment by amanjohar** [comment]
These sources come from `/etc/containers/registries.conf`. Here's a snippet:

```toml
[registries.search]
registries = ['docker.io', 'registry.fedoraproject.org', 'quay.io', 'registry.access.redhat.com', 'registry.centos.org']
```

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit-podman/issues/55#issuecomment-463604829_
