### ISSUE TITLE
User service appears to crash, but is still running

### ISSUE THREAD

**Issue by BrentonPoke** [cockpit-project/cockpit-podman#889]
Cockpit version: 260
Cockpit-podman version: 39
Podman version: 3.4.4
OS: Fedora 35

Steps to reproduce

1. Start a podman pod group through UI
2. bring it down with podman-compose down or the UI
3. Repeat 1-2 until bored
3. User service appears to crash.

I'm not sure who's fault it is, but sometimes it's still running in actuality. Other times, I have to restart the system. Cockpit-Podman looks like this right now, though the user service is still running according to systemctl:
![Screenshot from 2022-01-17 17-48-22](https://user-images.githubusercontent.com/6861851/149845039-48b0bdea-9400-4221-9a39-70026abb7e8c.png)
![Screenshot from 2022-01-17 17-13-24](https://user-images.githubusercontent.com/6861851/149845041-07aba3a9-39e9-490d-b50e-0fec6902dfa8.png)

**Comment by jelly** [comment]
Managed to reproduce it with for example:

```
podman play kube wordpress.yml
```

wordpress.yml
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-24T16:41:57Z"
  labels:
    app: project
  name: project
spec:
  containers:
  - args:
    - mariadbd
    image: docker.io/library/mariadb:latest
    name: wordpress-db
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: b3acddf0b1f450b08f4b9a022b00700f2123aa8e0ac1a303eb5519e80c1a91ce-pvc
  - args:
    - apache2-foreground
    image: docker.io/library/wordpress:latest
    name: wordpress-web
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: 57ed032976161677987ff2e49bf7536383ab225aa47a418f4aa37ed68d25bb0a-pvc
  restartPolicy: Always
  volumes:
  - name: b3acddf0b1f450b08f4b9a022b00700f2123aa8e0ac1a303eb5519e80c1a91ce-pvc
    persistentVolumeClaim:
      claimName: b3acddf0b1f450b08f4b9a022b00700f2123aa8e0ac1a303eb5519e80c1a91ce
  - name: 57ed032976161677987ff2e49bf7536383ab225aa47a418f4aa37ed68d25bb0a-pvc
    persistentVolumeClaim:
      claimName: 57ed032976161677987ff2e49bf7536383ab225aa47a418f4aa37ed68d25bb0a
status: {}
```

For me `podman ps` also hangs, is it the same for you?
